name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'
    - name: Configurar identidade Git
      run: |
        git config --global user.name "DeivSoares"
        git config --global user.email "deivisonsoares1610@outlook.com"
    - name: run install, build and test
      run: |
        npm install
        npm run build
        npm run deploy